import image1 from "./assets/image1.avif";
import image2 from "./assets/image2.avif";
import image3 from "./assets/image3.avif";
import image4 from "./assets/image4.avif";
import image5 from "./assets/image5.avif";
import image6 from "./assets/image6.avif";
import image7 from "./assets/image7.avif";
import image8 from "./assets/image8.avif";
import image9 from "./assets/image9.avif";
import image10 from "./assets/image10.avif";
import image11 from "./assets/image11.avif";
import image12 from "./assets/image12.avif";
import image13 from "./assets/image13.avif";
import image14 from "./assets/image14.webp";
import image15 from "./assets/image15.avif";
import image16 from "./assets/image16.avif";
import image17 from "./assets/image17.avif";
import image18 from "./assets/image18.avif";
import image19 from "./assets/image19.avif";
import image20 from "./assets/image20.avif";
import image21 from "./assets/image21.avif";
import image22 from "./assets/image22.avif";
import image23 from "./assets/image23.avif";
import image24 from "./assets/image24.avif";
import image25 from "./assets/image25.avif";

export const food_items = [
  {
    id: 1,
    food_name: "Pancakes",
    food_category: "breakfast",
    food_type: "veg",
    food_quantity: 1,
    food_image: image1,
    price: 499,
    rating: 4.7,
    description: "Soft and fluffy pancakes served with maple syrup.",
    popular: true,
  },
  {
    id: 2,
    food_name: "Chicken Soup",
    food_category: "soups",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image2,
    price: 399,
    rating: 4.6,
    description: "Healthy chicken soup with fresh vegetables.",
    popular: false,
  },
  {
    id: 3,
    food_name: "Minestrone Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image3,
    price: 349,
    rating: 4.5,
    description: "Classic Italian vegetable soup with herbs.",
    popular: false,
  },
  {
    id: 4,
    food_name: "Spaghetti Carbonara",
    food_category: "pasta",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image4,
    price: 999,
    rating: 4.9,
    description: "Creamy spaghetti with bacon and parmesan cheese.",
    popular: true,
  },
  {
    id: 5,
    food_name: "Veg Alfredo Pasta",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image5,
    price: 899,
    rating: 4.8,
    description: "Creamy Alfredo pasta loaded with fresh vegetables.",
    popular: true,
  },
  {
    id: 6,
    food_name: "Chicken Alfredo Pasta",
    food_category: "pasta",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image6,
    price: 1099,
    rating: 4.9,
    description: "Rich Alfredo pasta with grilled chicken pieces.",
    popular: true,
  },
  {
    id: 7,
    food_name: "Paneer Butter Masala",
    food_category: "main_course",
    food_type: "veg",
    food_quantity: 1,
    food_image: image7,
    price: 799,
    rating: 4.8,
    description: "Soft paneer cubes cooked in creamy tomato gravy.",
    popular: true,
  },
  {
    id: 8,
    food_name: "Chicken Biryani",
    food_category: "main_course",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image8,
    price: 1199,
    rating: 5.0,
    description: "Authentic dum biryani with aromatic basmati rice.",
    popular: true,
  },
  {
    id: 9,
    food_name: "Margherita Pizza",
    food_category: "pizza",
    food_type: "veg",
    food_quantity: 1,
    food_image: image9,
    price: 649,
    rating: 4.9,
    description: "Classic pizza with mozzarella cheese and basil.",
    popular: true,
  },

   {
    id: 10,
    food_name: "Pepperoni Pizza",
    food_category: "pizza",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image10,
    price: 749,
    rating: 4.8,
    description: "Loaded with pepperoni slices and melted mozzarella cheese.",
    popular: true,
  },
  {
    id: 11,
    food_name: "Veggie Burger",
    food_category: "burger",
    food_type: "veg",
    food_quantity: 1,
    food_image: image11,
    price: 499,
    rating: 4.6,
    description: "Crispy veggie patty with fresh lettuce and cheese.",
    popular: false,
  },
  {
    id: 12,
    food_name: "Chicken Burger",
    food_category: "burger",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image12,
    price: 599,
    rating: 4.8,
    description: "Juicy grilled chicken burger with fresh vegetables.",
    popular: true,
  },
  {
    id: 13,
    food_name: "Tomato Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image13,
    price: 299,
    rating: 4.4,
    description: "Fresh tomato soup seasoned with herbs and spices.",
    popular: false,
  },
  {
    id: 14,
    food_name: "Egg Sandwich",
    food_category: "breakfast",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image14,
    price: 349,
    rating: 4.5,
    description: "Toasted sandwich stuffed with egg and fresh vegetables.",
    popular: false,
  },
  {
    id: 15,
    food_name: "Mushroom Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image15,
    price: 349,
    rating: 4.6,
    description: "Creamy mushroom soup prepared with fresh mushrooms.",
    popular: false,
  },
  {
    id: 16,
    food_name: "Chicken Tikka Masala",
    food_category: "main_course",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image16,
    price: 1199,
    rating: 4.9,
    description: "Tender chicken tikka cooked in rich creamy gravy.",
    popular: true,
  },
  {
    id: 17,
    food_name: "Cheese Omelette",
    food_category: "breakfast",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image17,
    price: 399,
    rating: 4.7,
    description: "Fluffy omelette filled with melted cheese and herbs.",
    popular: true,
  },
  {
    id: 18,
    food_name: "Fettuccine Alfredo",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image18,
    price: 949,
    rating: 4.8,
    description: "Creamy Alfredo pasta with parmesan cheese and herbs.",
    popular: true,
  },

   {
    id: 19,
    food_name: "Garlic Bread",
    food_category: "pizza",
    food_type: "veg",
    food_quantity: 1,
    food_image: image19,
    price: 299,
    rating: 4.5,
    description: "Crispy garlic bread topped with butter, herbs, and cheese.",
    popular: false,
  },
  {
    id: 20,
    food_name: "Fish and Chips",
    food_category: "main_course",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image20,
    price: 1099,
    rating: 4.8,
    description: "Golden fried fish served with crispy French fries.",
    popular: true,
  },
  {
    id: 21,
    food_name: "Hash Browns",
    food_category: "breakfast",
    food_type: "veg",
    food_quantity: 1,
    food_image: image21,
    price: 249,
    rating: 4.4,
    description: "Golden crispy potato hash browns served hot.",
    popular: false,
  },
  {
    id: 22,
    food_name: "Vegetable Soup",
    food_category: "soups",
    food_type: "veg",
    food_quantity: 1,
    food_image: image22,
    price: 329,
    rating: 4.5,
    description: "Healthy vegetable soup made with fresh seasonal vegetables.",
    popular: false,
  },
  {
    id: 23,
    food_name: "Egg Fried Rice",
    food_category: "main_course",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image23,
    price: 599,
    rating: 4.7,
    description: "Classic fried rice tossed with eggs and fresh vegetables.",
    popular: true,
  },
  {
    id: 24,
    food_name: "Hawaiian Pizza",
    food_category: "pizza",
    food_type: "non_veg",
    food_quantity: 1,
    food_image: image24,
    price: 799,
    rating: 4.6,
    description: "A delicious combination of pineapple, ham, and mozzarella cheese.",
    popular: false,
  },
  {
    id: 25,
    food_name: "Pasta Primavera",
    food_category: "pasta",
    food_type: "veg",
    food_quantity: 1,
    food_image: image25,
    price: 899,
    rating: 4.7,
    description: "Fresh pasta tossed with colorful vegetables in a light sauce.",
    popular: true,
  }
];